[env]

[tasks.before-build]

[tasks.run]
dependencies = ["before-build"]
command = "cargo"
args = ["run", "${@}"]

[tasks.build]
dependencies = ["before-build"]
command = "cargo"
args = ["build", "${@}"]

[tasks.check]
dependencies = ["before-build"]
command = "cargo"
args = ["check"]

[tasks.watch]
dependencies = ["before-build"]
run_task = [{ name = ["fmt", "clippy", "test"] }]
watch = true

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.test]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
    "nextest",
    "--help",
] }
command = "cargo"
args = [
    "nextest",
    "run",
    "--status-level",
    "all",
    "--test-threads=1",
]

[tasks.clippy-ci]
dependencies = ["before-build"]
command = "cargo"
args = ["clippy", "--", "--no-deps", "-Dwarnings"]

[tasks.test-ci]
dependencies = ["before-build"]
command = "cargo"
args = [
    "nextest",
    "run",
    "--profile", "ci",
    "all",
    "--locked"
]
