name: Rust CI
on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

defaults:
  run:
    shell: bash
    working-directory: backend

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        # with:
        #   workspaces: |
        #     backend -> target

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable

      - name: Install cargo-related tools
        uses: taiki-e/install-action@v2
        with:
          tool: nextest,cargo-make

      - name: Tests compile
        run: cargo make test-ci --no-run --locked

      - name: Test
        run: cargo make test-ci

      - name: Clippy
        run: cargo make clippy-ci -- -Dwarnings

      - name: Rustfmt
        run: cargo make fmt -- --check
